<?php

declare(strict_types=1);

namespace Pko\ShippingCommon\Observers;

use Illuminate\Support\Facades\Log;
use Lunar\Models\Order;
use Pko\ShippingCommon\Jobs\CreateCarrierShipmentJob;
use Pko\ShippingCommon\Models\CarrierShipment;
use Pko\ShippingCommon\Models\Supplier;
use Pko\ShippingCommon\Shipping\ShipmentSplitter;

class OrderShipmentObserver
{
    public function updated(Order $order): void
    {
        if (! $order->wasChanged('payment_status')) {
            return;
        }

        if ($order->payment_status !== 'paid') {
            return;
        }

        $option = $order->shippingAddress?->shipping_option;
        if (! is_string($option) || ! str_contains($option, '.')) {
            return;
        }

        [$carrier, $serviceCode] = explode('.', $option, 2);

        if (! in_array($carrier, ['chronopost', 'colissimo'], true)) {
            return;
        }

        $this->createShipments($order, $carrier, $serviceCode);
    }

    private function createShipments(Order $order, string $carrier, string $serviceCode): void
    {
        $lines = $order->lines()->with(['purchasable.product'])->get();

        $supplierIds = $lines
            ->map(fn ($l) => $l->purchasable?->product?->pko_supplier_id ?? null)
            ->filter()
            ->unique()
            ->values();

        $suppliers = $supplierIds->isNotEmpty()
            ? Supplier::query()->whereIn('id', $supplierIds)->get()->keyBy('id')
            : collect();

        $groups = app(ShipmentSplitter::class)->split($lines, $suppliers);

        foreach ($groups as $group) {
            if ($group->origin === CarrierShipment::ORIGIN_WEKLO) {
                // Weklo stock → dispatch async job that calls the carrier SOAP API
                CreateCarrierShipmentJob::dispatch($order->id, $carrier, $serviceCode, $group->origin);
            } else {
                // Supplier-handled shipment: record the intent but do NOT call the carrier API.
                // supplier_direct  → supplier ships directly to client, no label generated by Weklo.
                // supplier_via_weklo → supplier ships to Weklo for re-shipment; label created later.
                CarrierShipment::query()->firstOrCreate(
                    [
                        'order_id' => $order->id,
                        'carrier' => $carrier,
                        'origin' => $group->origin,
                    ],
                    [
                        'service_code' => $serviceCode,
                        'status' => CarrierShipment::STATUS_PENDING,
                    ],
                );

                Log::info('Supplier shipment recorded (no carrier API call)', [
                    'order_id' => $order->id,
                    'carrier' => $carrier,
                    'origin' => $group->origin,
                ]);
            }
        }
    }
}
