<?php

declare(strict_types=1);

namespace Pko\ShippingCommon\Observers;

use Illuminate\Support\Facades\Log;
use Lunar\Models\Order;
use Pko\ShippingCommon\Jobs\CreateCarrierShipmentJob;
use Pko\ShippingCommon\Models\CarrierShipment;
use Pko\ShippingCommon\Models\Supplier;
use Pko\ShippingCommon\Shipping\ShipmentSplitter;

class OrderShipmentObserver
{
    /** Lunar order statuses that mean the order has been paid. */
    private const PAID_STATUSES = ['paid', 'payment-received'];

    /*
     * Pourquoi pas de hook `created()` : au moment où la commande est créée, ses
     * adresses ne le sont pas encore (`CreateOrderAddresses` s'exécute après
     * `FillOrderFromCart`). Un observer `created` ne verrait donc jamais de
     * `shipping_option` — une commande importée déjà payée reste sans étiquette.
     * Ce trou est couvert par la commande `shipping:backfill-shipments`.
     */

    public function updated(Order $order): void
    {
        // Lunar stores the paid state in `status` (the Stripe addon maps a succeeded
        // PaymentIntent to `payment-received`); there is no `payment_status` column.
        if (! $order->wasChanged('status')) {
            return;
        }

        if (! in_array($order->status, self::PAID_STATUSES, true)) {
            return;
        }

        $this->dispatchForOrder($order);
    }

    private function dispatchForOrder(Order $order): void
    {
        $option = $order->shippingAddress?->shipping_option;
        if (! is_string($option) || ! str_contains($option, '.')) {
            return;
        }

        [$carrier, $serviceCode] = explode('.', $option, 2);

        if (! in_array($carrier, ['chronopost', 'colissimo'], true)) {
            return;
        }

        $this->createShipments($order, $carrier, $serviceCode);
    }

    private function createShipments(Order $order, string $carrier, string $serviceCode): void
    {
        // productLines() exclut la ligne shipping (type=shipping) dont le purchasable
        // est un Lunar\DataTypes\ShippingOption (value-object, non-Eloquent) : l'eager-load
        // MorphTo de purchasable planterait sinon en ArgumentCountError.
        $lines = $order->productLines()->with(['purchasable.product'])->get();

        $supplierIds = $lines
            ->map(fn ($l) => $l->purchasable?->product?->pko_supplier_id ?? null)
            ->filter()
            ->unique()
            ->values();

        $suppliers = $supplierIds->isNotEmpty()
            ? Supplier::query()->whereIn('id', $supplierIds)->get()->keyBy('id')
            : collect();

        $groups = app(ShipmentSplitter::class)->split($lines, $suppliers);

        foreach ($groups as $group) {
            if ($group->origin === CarrierShipment::ORIGIN_WEKLO) {
                // Weklo stock → dispatch async job that calls the carrier SOAP API
                CreateCarrierShipmentJob::dispatch($order->id, $carrier, $serviceCode, $group->origin);
            } else {
                // Supplier-handled shipment: record the intent but do NOT call the carrier API.
                // supplier_direct  → supplier ships directly to client, no label generated by Weklo.
                // supplier_via_weklo → supplier ships to Weklo for re-shipment; label created later.
                CarrierShipment::query()->firstOrCreate(
                    [
                        'order_id' => $order->id,
                        'carrier' => $carrier,
                        'origin' => $group->origin,
                    ],
                    [
                        'service_code' => $serviceCode,
                        'status' => CarrierShipment::STATUS_PENDING,
                    ],
                );

                Log::info('Supplier shipment recorded (no carrier API call)', [
                    'order_id' => $order->id,
                    'carrier' => $carrier,
                    'origin' => $group->origin,
                ]);
            }
        }
    }
}
